const SUPABASE_URL = 'https://ajtqqymrjbahfmcibijc.supabase.co';
const SUPABASE_KEY = 'sb_publishable_BI6qwdXTo5Fh_byTlu319w_ELOn8l0C';
const WMS_STORAGE_KEY = 'ruangstok-data';
let clientPromise;
function loadSupabaseSdk(){return new Promise((resolve,reject)=>{if(window.supabase)return resolve(window.supabase);const s=document.createElement('script');s.src='https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2';s.onload=()=>resolve(window.supabase);s.onerror=reject;document.head.appendChild(s)})}
async function getClient(){if(!clientPromise)clientPromise=loadSupabaseSdk().then(sdk=>sdk.createClient(SUPABASE_URL,SUPABASE_KEY));return clientPromise}
function localState(){try{return JSON.parse(localStorage.getItem(WMS_STORAGE_KEY))||null}catch{return null}}
function writeLocal(state){localStorage.setItem(WMS_STORAGE_KEY,JSON.stringify(state))}
async function readRemote(){const client=await getClient();const [{data:products,error:pErr},{data:movements,error:mErr}]=await Promise.all([client.from('products').select('id,name,category,unit,price,opening,min,icon,tone,supplier').order('id'),client.from('stock_movements').select('transaction_no,product_id,movement_type,qty,reference_no,movement_date').order('created_at',{ascending:false})]);if(pErr)throw pErr;if(mErr)throw mErr;const byId=Object.fromEntries((products||[]).map(p=>[p.id,p.name]));return{products:(products||[]).map(p=>({...p,min:Number(p.min||0),opening:Number(p.opening||0),price:Number(p.price||0)})),transactions:(movements||[]).map(m=>({id:m.transaction_no,date:m.movement_date,product:byId[m.product_id]||m.product_id,type:m.movement_type==='adjustment'?'in':m.movement_type,qty:Number(m.qty),ref:m.reference_no||''}))}}
async function syncRemoteToLocal(){const remote=await readRemote();const local=localState();if(remote.products.length){writeLocal(remote);return remote}if(local&&local.products&&local.products.length){await pushLocalToRemote(local);return local}writeLocal(remote);return remote}
async function pushLocalToRemote(state){const client=await getClient();if(!state)return;const products=(state.products||[]).map(p=>({id:p.id,name:p.name,category:p.category,unit:p.unit||'unit',price:Number(p.price||0),opening:Number(p.opening||0),min:Number(p.min||0),icon:p.icon||'',tone:p.tone||'',supplier:p.supplier||null}));if(products.length){const {error}=await client.from('products').upsert(products,{onConflict:'id'});if(error)throw error}const names=Object.fromEntries((state.products||[]).map(p=>[p.name,p.id]));for(const t of(state.transactions||[]).slice().reverse()){const {error}=await client.rpc('record_stock_movement',{p_transaction_no:t.id,p_product_id:names[t.product]||t.product,p_movement_type:t.type,p_qty:Number(t.qty||0),p_reference_no:t.ref||null,p_movement_date:t.date});if(error)throw error}return true}
async function refresh(){const remote=await readRemote();if(remote.products.length)writeLocal(remote);return remote}
function subscribeRealtime(){getClient().then(client=>{client.channel('wms-live').on('postgres_changes',{event:'*',schema:'public',table:'products'},()=>refresh().then(()=>window.dispatchEvent(new CustomEvent('wms:refresh'))).catch(console.error)).on('postgres_changes',{event:'*',schema:'public',table:'stock_movements'},()=>refresh().then(()=>window.dispatchEvent(new CustomEvent('wms:refresh'))).catch(console.error)).subscribe()}).catch(console.error)}
window.WMSBackend={syncRemoteToLocal,pushLocalToRemote,refresh,SUPABASE_URL,getClient};
(async()=>{try{const originalSetItem=Storage.prototype.setItem;let syncing=false;Storage.prototype.setItem=function(key,value){originalSetItem.call(this,key,value);if(key===WMS_STORAGE_KEY&&!syncing){syncing=true;pushLocalToRemote(JSON.parse(value)).catch(console.error).finally(()=>{syncing=false})}};await syncRemoteToLocal();subscribeRealtime();document.documentElement.dataset.supabase='connected';const sync=document.querySelector('.sync-card small');if(sync)sync.textContent='Terhubung ke Supabase';window.dispatchEvent(new CustomEvent('wms:refresh'))}catch(error){console.error('Supabase connection failed:',error);const sync=document.querySelector('.sync-card small');if(sync)sync.textContent='Mode lokal — Supabase gagal terhubung'}})();